/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as InsuranceIndexRouteImport } from './routes/insurance/index'
import { Route as InsuranceSlugRouteImport } from './routes/insurance/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceIndexRoute = InsuranceIndexRouteImport.update({
  id: '/insurance/',
  path: '/insurance/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceSlugRoute = InsuranceSlugRouteImport.update({
  id: '/insurance/$slug',
  path: '/insurance/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/quote': typeof QuoteRoute
  '/insurance/$slug': typeof InsuranceSlugRoute
  '/insurance/': typeof InsuranceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/quote': typeof QuoteRoute
  '/insurance/$slug': typeof InsuranceSlugRoute
  '/insurance': typeof InsuranceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/quote': typeof QuoteRoute
  '/insurance/$slug': typeof InsuranceSlugRoute
  '/insurance/': typeof InsuranceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/contact' | '/quote' | '/insurance/$slug' | '/insurance/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/quote' | '/insurance/$slug' | '/insurance'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/quote'
    | '/insurance/$slug'
    | '/insurance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  QuoteRoute: typeof QuoteRoute
  InsuranceSlugRoute: typeof InsuranceSlugRoute
  InsuranceIndexRoute: typeof InsuranceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/': {
      id: '/insurance/'
      path: '/insurance'
      fullPath: '/insurance/'
      preLoaderRoute: typeof InsuranceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/$slug': {
      id: '/insurance/$slug'
      path: '/insurance/$slug'
      fullPath: '/insurance/$slug'
      preLoaderRoute: typeof InsuranceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  QuoteRoute: QuoteRoute,
  InsuranceSlugRoute: InsuranceSlugRoute,
  InsuranceIndexRoute: InsuranceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
